### ISSUE TITLE
Unrecognised endpoint: eu-central-1

### ISSUE THREAD

**Issue by vvvvalvalval** [laurilehmijoki/s3_website#183]
Hi, trying to push my website to a Frankurt S3 bucket, I got the following error: 

```
[fail] Could not load the site: Unrecognised endpoint: eu-central-1
```

I tried with both `eu-central-1` and `s3.eu-central-1.amazonaws.com` as endpoint values.

Here is my configuration: 

```yaml
s3_id: xxxxxxxxxxxxx
s3_secret: xxxxxxxxxxxxx
s3_bucket: staging-gareslive.bandsquare.com

# Below are examples of all the available configurations.
# See README for more detailed info on each of them.

# site: path-to-your-website

# index_document: index.html
# error_document: error.html

# max_age:
#   "assets/*": 6000
#   "*": 300

gzip: true
#   - .html
#   - .css
#   - .md
# gzip_zopfli: true

# See http://docs.aws.amazon.com/general/latest/gr/rande.html#s3_region for valid endpoints
s3_endpoint: eu-central-1

# ignore_on_server: that_folder_of_stuff_i_dont_keep_locally

# exclude_from_upload:
#   - those_folders_of_stuff
#   - i_wouldnt_want_to_upload

# s3_reduced_redundancy: true

# cloudfront_distribution_id: your-dist-id

# cloudfront_distribution_config:
#   default_cache_behavior:
#     min_TTL: <%= 60 * 60 * 24 %>
#   aliases:
#     quantity: 1
#     items:
#       CNAME: your.website.com

# cloudfront_invalidate_root: true

# concurrency_level: 5

# redirects:
#   index.php: /
#   about.php: about.html
#   music-files/promo.mp4: http://www.youtube.com/watch?v=dQw4w9WgXcQ

# routing_rules:
#   - condition:
#       key_prefix_equals: blog/some_path
#     redirect:
#       host_name: blog.example.com
#       replace_key_prefix_with: some_new_path/
#       http_redirect_code: 301
```
