### ISSUE TITLE
Two aliased CNAMES are set, but only one is sent on cfg apply

### ISSUE THREAD

**Issue by yanokwa** [laurilehmijoki/s3_website#191]
I am using s3_website-2.12.2 on Mac OS X 10.11.

In my `s3_website.yml` file, I have the following
```yml
cloudfront_distribution_id: my_id
cloudfront_distribution_config:
  default_cache_behavior:
    min_TTL: <%= 60 * 60 * 24 %>
  aliases:
    quantity: 2 
    items:
      CNAME: my_domain.com
      CNAME: www.my_domain.com
```

When I run `s3_website cfg apply`, I get this error message: Detected an existing CloudFront distribution (id my_id). AWS API call failed:
```xml	
<?xml version="1.0"?>
<ErrorResponse xmlns="http://cloudfront.amazonaws.com/doc/2012-07-01/"><Error><Type>Sender</Type><Code>InconsistentQuantities</Code><Message>The specified quantity of Aliases (2) does not match the actual quantity supplied (1).</Message></Error><RequestId>my_request_id</RequestId></ErrorResponse> (GenericError)
```

It seems s3_website isn't sending both CNAMES.
