### ISSUE TITLE
Adding custom headers

### ISSUE THREAD

**Issue by derekperkins** [laurilehmijoki/s3_website#237]
I'd like to add some custom headers. My current question revolves around some security headers listed below, but it would also be very nice to be able to set arbitrary headers somehow.

- `X-Frame-Options`
- `Content-Security-Policy`
- `X-XSS-Protection`

**Comment by laurilehmijoki** [comment]
How would you like to express the headers in the config file?

**Comment by derekperkins** [comment]
I think it could be almost identical to the `max age` setup, just with one extra nested array.

```
max_age:
  "*.html": 
    X-XSS-Protection: 1
  "assets/*": 
    X-Frame-Options: DENY
  "*": 
    X-Frame-Options: SAMEORIGIN
```
