### ISSUE TITLE
Update documentation for CloudFront aliases

### ISSUE THREAD

**Issue by dchancogne** [laurilehmijoki/s3_website#270]
The documentation provides the following example on using the config to create aliases:

```
cloudfront_distribution_config:
  aliases:
    quantity: 1
    items:
      - your.website.com
```

I could not get this to work until I found an example in one of the issue that worked for me:

```
cloudfront_distribution_config:
  aliases:
    quantity: 1
    items:
      CNAME: your.website.com
```

If this is the correct syntax, please update the README.
