### ISSUE TITLE
301 redirects don't work

### ISSUE THREAD

**Issue by iloveip** [laurilehmijoki/s3_website#280]
Hi there,
I have the following settings in my `s3_website.yml` file to create 301 redirects for SEO purposes from `/kb/page` to `/kb/page/`:
```
redirects:
  kb/insurance-deductions.html: /kb/insurance-deductions/
  kb/tax-return.html: /kb/tax-return/
  kb/application.html: /kb/application/
  kb/documents.html: /kb/documents/
  kb/online.html: /kb/online/
treat_zero_length_objects_as_redirects: true
```

But this doesn't seem to work. Here is the answer I get from Googlebot:
```
HTTP/1.1 302 Found
```
