### ISSUE TITLE
Suggestion: add '--env' flag to 's3_website push' command

### ISSUE THREAD

**Issue by zulhfreelancer** [laurilehmijoki/s3_website#289]
I would like to suggest that we have this inside the _s3_website.yml_ file:

```
production:
    s3_id: ...
    s3_secret: ...
    s3_bucket: ...

staging:
    s3_id: ...
    s3_secret: ...
    s3_bucket: ...
```

And, when deploying the site, we can use `--env` flag like this:

```
s3_website push --env staging
s3_website push --env production
```

I know that we can use ERB inside the YAML file and use dotenv to set different S3 credentials. But, having `if` and `else` inside the YAML file make it look longer and less elegant.

I know, by having `if` and `else` inside the YAML file, we can simply deploy with this style:

```
ENV=staging s3_website push
ENV=production s3_website push
```

I still prefer to use `--env` flag. I can help with this. I just need some guide/reference/tutorial resources. Please share the resources here if you have it.
