### ISSUE TITLE
Redirects cause download of zero-byte file

### ISSUE THREAD

**Issue by decisao** [laurilehmijoki/s3_website#304]
Hi,

When I specify redirects, like this:

```
cloudfront_distribution_config:
      default_cache_behavior:
          min_TTL: <%= 60 * 60 * 24 * 8 %>
      http_version: http2
      aliases:
          quantity: 1
          items:
              CNAME: <mydomain>
cloudfront_invalidate_root: true
cloudfront_wildcard_invalidation: true
treat_zero_length_objects_as_redirects: true
redirects:
  contato: /atendimento.html
  atendimento: /atendimento.html
  expresso: /expresso.html
  downloads: /downloads.html
```

On acesse <mydomain>/contato it does not redirect to <mydomain>/atendimento.html
It downloads a zero-byte file called "contato".

Using s3_website 3.4

How to fix this?

Elieser
