### ISSUE TITLE
Getting "Bucket must be addressed using specified endpoint" on `cfg apply`

### ISSUE THREAD

**Issue by jedfoster** [laurilehmijoki/s3_website#40]
Perhaps I'm doing it wrong, but I keep getting this error when I run `s3_website cfg apply`:

``` shell
jed:~/Dropbox/Code/Sites/jedfoster.com [git:master+?]  
→ s3_website cfg apply
Applying the configurations in s3_website.yml on the AWS services ...
/Users/jed/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/configure-s3-website-1.5.0/lib/configure-s3-website/http_helper.rb:54:in `call_api': AWS API call failed: (GenericError)
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>PermanentRedirect</Code><Message>The bucket you are attempting to access must be addressed using the specified endpoint. Please send all future requests to this endpoint.</Message><RequestId>7B02DC9DEF00EFB1</RequestId><Bucket>assets.jedfoster.com</Bucket><HostId>ZU2boFGltJbUIQE0IGgJkFnpMaLyOmFh7bBJcznJjm9e6aGKHW29RrK6jgUlKQRi</HostId><Endpoint>assets.jedfoster.com.s3.amazonaws.com</Endpoint></Error>
    from /Users/jed/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/configure-s3-website-1.5.0/lib/configure-s3-website/http_helper.rb:7:in `call_s3_api'
    from /Users/jed/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/configure-s3-website-1.5.0/lib/configure-s3-website/s3_client.rb:34:in `enable_website_configuration'
    from /Users/jed/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/configure-s3-website-1.5.0/lib/configure-s3-website/s3_client.rb:12:in `configure_website'
    from /Users/jed/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/configure-s3-website-1.5.0/lib/configure-s3-website/runner.rb:4:in `run'
    from /Users/jed/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/configure-s3-website-1.5.0/bin/configure-s3-website:12:in `<top (required)>'
    from /Users/jed/.rbenv/versions/1.9.3-p194/bin/configure-s3-website:23:in `load'
    from /Users/jed/.rbenv/versions/1.9.3-p194/bin/configure-s3-website:23:in `<main>'
```

Here's my `s3_website.yml` file:

``` yaml
s3_id: XXX
s3_secret: XXX
s3_bucket: assets.jedfoster.com

# Below are examples of all the available configurations.
# See README for more detailed info on each of them.

# max_age:
#   "assets/*": 6000
#   "*": 300

gzip:
  - .html
  - .css
  - .md
  - .js

# s3_endpoint:  

# ignore_on_server: that_folder_of_stuff_i_dont_keep_locally

# s3_reduced_redundancy: true

# cloudfront_distribution_id: your-dist-id

# cloudfront_distribution_config:
#   default_cache_behavior:
#     min_TTL: <%= 60 * 60 * 24 %>
#   aliases:
#     quantity: 1
#     items:
#       CNAME: your.website.com

# cloudfront_invalidate_root: true

# concurrency_level: 100

redirects:
  index.php: /
#   about.php: about.html
#   music-files/promo.mp4: http://www.youtube.com/watch?v=dQw4w9WgXcQ

# routing_rules:
#   - condition:
#       key_prefix_equals: blog/some_path
#     redirect:
#       host_name: blog.example.com
#       replace_key_prefix_with: some_new_path/
#       http_redirect_code: 301
```

`s3_website cfg apply` "works" if I set `s3_bucket` to the endpoint listed on my AWS console (under "Static Website Hosting"), but the resulting bucket is `assets.jedfoster.com.s3-website-us-west-2.amazonaws.com` which I don't think is correct.

Is this a bug, or am I doing it wrong?
