### ISSUE TITLE
Getting "I can't parse the file s3_website.yml. It should look like this:" when using seemingly valid file.

### ISSUE THREAD

**Issue by rmontgomery429** [laurilehmijoki/s3_website#71]
I have a file that looks like this:

``` yaml
s3_id: <%= ENV['UTP_S3_ID'] %>
s3_secret: <%= ENV['UTP_S3_SECRET'] %>
s3_bucket: <%= ENV['UTP_S3_BUCKET'] %>

max_age:
  "assets/*.css": <%= 60 * 60 * 24 * 365 %>
  "assets/*.css.gz": <%= 60 * 60 * 24 * 365 %>
  "assets/*.js": <%= 60 * 60 * 24 * 365 %>
  "assets/*.js.gz": <%= 60 * 60 * 24 * 365 %>
  "assets/*.eot": <%= 60 * 60 * 24 * 365 %>
  "assets/*.eot.gz": <%= 60 * 60 * 24 * 365 %>
  "assets/*.svg": <%= 60 * 60 * 24 * 365 %>
  "assets/*.svg.gz": <%= 60 * 60 * 24 * 365 %>
  "assets/*.ttf": <%= 60 * 60 * 24 * 365 %>
  "assets/*.ttf.gz": <%= 60 * 60 * 24 * 365 %>
  "assets/*.woff": <%= 60 * 60 * 24 * 365 %>
  "assets/*.woff.gz": <%= 60 * 60 * 24 * 365 %>
  "*": <%= 60 * 60 * 6 %>

gzip:
  - .gz

concurrency_level: 5
```

https://gist.github.com/rmontgomery429/4ca5a2371161c840cf34

This appears to be fine, but the parser doesn't like it. What am I missing?
